[package]
name = "scorched"
description = "A simple logging library for scorching all those pesky bugs."
version = "0.2.2"
edition = "2021"
license = "Apache-2.0"

[dependencies]
owo-colors = "3.5.0"
chrono = "0.4.26"